# Default values for juicefs-s3-gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: juicedata/mount
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "ce-v1.0.4"

port: 9000
metricsPort: 9567
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

service:
  type: ClusterIP

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 5000m
    memory: 5Gi
  requests:
    cpu: 1000m
    memory: 1Gi

hostNetwork: false
nodeSelector: {}
tolerations: []
affinity: {}

secret:
  # -- The JuiceFS file system name.
  name: ""
  # -- Connection URL for metadata engine (e.g. Redis). Read [this document](https://juicefs.com/docs/community/databases_for_metadata) for more information.
  metaurl: ""
  # -- Object storage type, such as `s3`, `gs`, `oss`. Read [this document](https://juicefs.com/docs/community/how_to_setup_object_storage) for the full supported list.
  storage: ""
  # -- Access key for object storage
  accessKey: ""
  # -- Secret key for object storage
  secretKey: ""
  # -- Bucket URL. Read [this document](https://juicefs.com/docs/community/how_to_setup_object_storage) to learn how to setup different object storage.
  bucket: ""

# -- JuiceFS format options. Separated by spaces. Read [this document](https://juicefs.com/docs/community/command_reference#juicefs-format) to learn how to set different format options.
# Example: "--inodes=1000000 --block-size=4M"
formatOptions: ""

# -- Gateway Options. Separated by spaces. Read [this document](https://juicefs.com/docs/community/command_reference#juicefs-gateway) to learn how to set different gateway options.
options: ""
# Example: "--get-timeout=60 --put-timeout=60"
